steps:
  # Build the image in a single place for all parallel steps to leverage the same image.
  - name: ':docker: :package: e2e'
    plugins:
      'docker-compose#v3.0.3':
        build:
          - e2e-test
          - e2e-server
          - e2e-server-healthy
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders

  # Wait for the above image(s) to be built
  - wait

  - name: ':eye: Visual regression tests'
    # command: yarn add puppeteer && yarn vrt
    # commands:
    #   - 'chmod +x ./vrt/run.sh'
    #   - './vrt/run.sh'
    command: node vrt/run.js
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
        pull:
          - e2e-server
          - e2e-server-healthy
    agents:
      queue: builders
    artifact_paths:
      - '__artifacts__/*.png'
      - '__artifacts__/*.txt'
